<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=koi8-r">
<meta http-equiv="Cache-Control" content="no-cache">
<title>Информация Билинга</title>
<style>
.txt8
	{
	font-size: 10pt;
	font-family: "Arial, Helvetica, sans-serif";
	font-weight: normal;
	}
.txt9
	{
	font-size: 11pt;
	font-family: "Arial, Helvetica, sans-serif";
	font-weight: normal;
	}
.b1c {  background-color: #E8E8E8}
.b2c {  background-color: #B8B8B8}
</style>
</head>

<body class='txt9'>
<?php
header("Expires: ".gmdate("D, d M Y H:i:s",time()+2)." GMT");
?>
<center>
<h3>Состояние счета</h3>
<?php

   $showlog = 0;  // =1 - Показать форму просмотра журнала доступа (через www.oganer.net)

   $remote_addr = $HTTP_SERVER_VARS['REMOTE_ADDR'];

   $lights  = array("green", "yellow", "red");
   $tariffs = array("анлимит", "обычный");
   $states  = array("счет удален", "счет поврежден", "счет заморожен", "счет блокирован", "средства исчерпаны", "баланс близок к нулю", "активен");

   $light  = 0;
   $tariff = 1;
   $state  = 6;

// Mode (0 - Money, 1 - Unlimit (don't show ballance))
   $mode   = 0;  

   $acc_info = exec("/usr/local/bin/getacc2 $remote_addr", $s);
   $ret = explode(" ", $acc_info);

   if ($ret[0] >= 0) 
   {
     $tariff = 1;        // normal
     if (($ret[1] & 16) != 0) 
     {  $tariff = 0;
        $mode   = 1;
     }

// State/light
     $state = 6;
     $light = 0;
     if (($ret[1] & 15) != 0) $light = 2;  // red
     if (($ret[1] & 1)  == 1) $state = 0;  // deleted
     if (($ret[1] & 3)  == 2) $state = 1;  // broken
     if (($ret[1] & 7)  == 4) $state = 2;  // frozen
     if (($ret[1] & 15) == 8) $state = 3;  // off

     if ($light != 2 && $mode == 0)
     {  if ($ret[2] <= 0)
        {  $state = 4;
           $light = 2; 
        }
        else if ($ret[2] <= 1000)
        {  $state = 5;
           $light = 1;
        }
     }

     echo "<table class='txt8' cellspacing=1 cellpadding=4>\n";
     echo "<tr>";
     echo "<td colspan=3 valign='middle'><font size=4 color='".$lights[$light]."'>";
     switch($light)
     {  case 0:
          echo "Интернет доступен";
          break;
        case 1:
          echo "Внимание: ".$states[$state]." (интернет доступен)";
          break;
        case 2:
          echo "Интернет недоступен - ".$states[$state];
     }
     echo "</font></td></tr></table>\n";

     echo "<table class='txt8' border=0><tr><td width='65'>";
     echo "&nbsp;</td><td width='300'>\n";

     echo "<table class='txt8' cellspacing=1 cellpadding=4>\n";
     echo "<tr><td class='b1c' width='175'>Хост</td><td class='b1c' width='120'>".$remote_addr."</td></tr>\n";
     echo "<tr><td class='b1c'>Счет</td><td class='b1c'>".$ret[0]."</td></tr>\n";
     echo "<tr><td class='b1c'>Состояние</td class='b1c'><td class='b1c'>";
     echo "<font color='".($light==1 ? "brown" : $lights[$light])."'>";
     echo $states[$state];
     if ($state > 1)
     {  echo "<tr><td class='b1c'>Режим</td><td class='b1c'>".$tariffs[$tariff]."</td></tr>\n";
     }
     echo "</font></td></tr>\n";
     echo "</table>";

     echo "</td>";

     if ($mode == 0 && $state > 1)
     {  echo "<td valign=top><table class='txt8' cellspacing=1 cellpadding=4 width='200'>\n";
        echo "<tr><td align=center><font size=3>Баланс счета</font></td></tr><tr><td align=center>";
        echo "<font size=6".($ret[2] > 1000 ? "":($ret[2] <= 0 ? " color='red'":" color='yellow'")).">";
        echo sprintf("%+.2f",($ret[2] / 100));
        echo "<font><td></tr>\n";
        echo "</tr></table></td>\n";
     }

     echo "</tr></table>\n";

     $rc = 1;

     if ($state >= 0 && $state <= 3) 
     {  echo "<table class='txt9'><tr width='100%'><td width='30'>&nbsp;</td><td>";
        switch ($state)
        {  case 0:
              echo "&nbsp;&nbsp;&nbsp;Данный счет был удален, за разъяснениями обратитесь в ";
              echo "службу поддержки.";
              break;
           case 1:
              echo "&nbsp;&nbsp;&nbsp;Счет был поврежден врезультате сбоя. Сообщите об этой ошибке в ";
              echo "службу поддержки.";   
              break;
           case 2:
              echo "&nbsp;&nbsp;&nbsp;Операции по счету были заморожены системным администратором. ";
              echo "Свяжитесь со службой поддержки.";
              break;  
           case 3:
              if ($rc)
              {  echo "&nbsp;&nbsp;&nbsp;Счет заблокирован Вами (или другим пользователем Вашего счета).<br>";
                 echo "Для возвращения счета в нормальное состояние нажмите кнопку ниже.";
              }
              else
              {  echo "&nbsp;&nbsp;&nbsp;Счет заблокирован мастер-пользователем и может быть ";
                 echo "разблокирован им же или другим пользователем с правами на управление счетом. ";
                 echo "Свяжитесь с мастер-пользователем или службой поддержки.";
              }
        }        
        echo "</td><td width='30'>&nbsp;</td></tr></table>";
     } 

     if ($rc != 0 && ($ret[1] & 7) == 0)  
     {  echo "<hr>";
        echo "<table class='txt9'><tr>";
        echo "<form action='acc_".(($ret[1] & 8) ? "on":"off").".phtml' method='post'>";
        echo "<td width='30'>&nbsp;</td><td valign='middle' width='150'>Управление счетом:</td>";
        echo "<td><input type=submit value='".(($ret[1] & 8) ? "Разблокировать":"Блокировать")."'></td>";
        echo "</form>";
        echo "<tr></table>";
     } 

     $dt = getdate();
     $mday = $dt['mday'];
     $mon  = $dt['mon'];
     $year = $dt['year'];

     $months = array(1 => "января", "февраля", "марта", "апреля", "мая", "июня", "июля", "августа", "сентября", "октября", "ноября", "декабря");

// transactions log
?>
<hr>
<table class="txt9" border=0>
  <tr width="100%">
   <td align='left' valign='middle' width='150'>Журнал операций по счету</td>
   <td align='right' valign="middle">за </td>
<form method='post' name='stat' action='stat.phtml'>
   <td align=center valign="middle">
   <input name='days' type='text' size='2' maxlength='2' style='background-color: #E6FAFF' value='1'>
</td>
    <td align=center valign="middle">дней, </td>
    <td align=center valign="middle">с:</td>
    <td align=center valign="middle">
    <input name='mday' type='text' size='2' maxlength='2' style='background-color: #E6FAFF'
<?php
   echo "value ='".$mday."'";
?>
>
   <select name='mon' size='1' style='background-color: #E6FAFF'>
<?php

   $i = $mon;
   do
   {  echo "<option value=$i>$months[$i]";
      $i++;
      if ($i > 12) $i = 1;
   } while ($i != $mon);
?>
   </select>
   <input name='year' type='text' size='4' maxlength='4' style='background-color: #E6FAFF'
<?php
   echo "value ='".$year."'";
?>
   >
    </td>
    <td align=center valign="middle">
    <input name='verbose' type='checkbox' value='1'>
    </td>
    <td align=center valign="middle">подробно</td>
    <td align=center valign="middle">
   <input value='Показать' type='submit' size='5'>
    </td>
  </tr>
</form>
</table>
<?php
// access log
if ($showlog != 0)
{
?>
<hr>
<table class="txt9" border=0>
  <tr width="100%">
   <td align='left' valign='middle' width='150'>Журнал доступа к Интернету<font color='red'>*</font></td>
   <td align='right' valign="middle">за </td>
<form method='post' name='stat' action='http://www.oganer.net/logstat.html'>
   <td align=center valign="middle">
   <input name='days' type='text' size='2' maxlength='2' style='background-color: #E6FAFF' value='1'>
</td>
    <td align=center valign="middle">дней, </td>
    <td align=center valign="middle">с:</td>
    <td align=center valign="middle">
    <input name='mday' type='text' size='2' maxlength='2' style='background-color: #E6FAFF'
<?php
   echo "value ='".$mday."'";
?>
>
   <select name='mon' size='1' style='background-color: #E6FAFF'>
<?php

   $i = $mon;
   do
   {  echo "<option value=$i>$months[$i]";
      $i++;
      if ($i > 12) $i = 1;
   } while ($i != $mon);
?>
   </select>
   <input name='year' type='text' size='4' maxlength='4' style='background-color: #E6FAFF'
<?php
   echo "value ='".$year."'";
?>
   >
    </td>
    <td align=center valign="middle">
    <input name='verbose' type='checkbox' value='1'>
    </td>
    <td align=center valign="middle">подробно</td>
    <td align=center valign="middle">
   <input value='Показать' type='submit' size='5'>
    </td>
  </tr>
</form>
</table>
* <small>Информация предоставляется ЗАО &quot;Оганер-Сервис&quot; в отладочном режиме. Работа и
верность данных не гарантируются.</small>
<?php
}
echo "<hr>";


   }
   else
   {  
      if ($ret[0] == (-1)) // Account not found
      {
         echo "<table class='txt8' cellspacing=1 cellpadding=4>\n";
         echo "<tr>";
         echo "<td colspan=3 valign='middle'><font size=4 color='red'>";
         echo "Не найден счет для Вашего адреса";
         echo "</font></td></tr></table>\n";
         echo "<table class='txt9'><tr width='100%'><td width='30'>&nbsp;</td><td>";

            echo "&nbsp;&nbsp;&nbsp;Извините, мы не предоставляем услуг Интернета на адрес ($remote_addr) с которого Вы зашли. ";
            echo "Вероятнее всего, Вы забыли соединиться с VPN-cервером, или прописали дополнительный маршрут включающий ";
            echo "этот веб-сервер.<br><br>";
            echo "&nbsp;&nbsp;&nbsp;Cтраница билинга работает только при активном VPN-подключении.";
            echo "<br><br>";
            echo "&nbsp;&nbsp;&nbsp;Проверьте Ваши настройки и/или перезвоните в службу поддержки";

         echo "</td><td width='30'>&nbsp;</td></tr></table>";

      }
      else
      {
         echo "<table class='txt8' cellspacing=1 cellpadding=4>\n";
         echo "<tr>";
         echo "<td colspan=3 valign='middle'><font size=4 color='red'>";
         echo "Информация временно недоступна - ";
         if ($ret[0] == (-52)) echo "сбой связи с сервисом";
         else echo "программный сбой";
         echo "</font></td></tr></table>\n";
         echo "<table class='txt9'><tr width='100%'><td width='30'>&nbsp;</td><td>";

         if ($ret[0] == (-52))
         {  echo "&nbsp;&nbsp;&nbsp;Извините, информация недоступна всвязи с аппаратным сбоем или работами на ";
            echo "сервере.<br><br>";
            echo "&nbsp;&nbsp;&nbsp;Информацию об состоянии Вашего счета вы можете получить в службе поддержки";
         }
         else
         {  echo "&nbsp;&nbsp;&nbsp;Извините, информация недоступна из-за программного сбоя. ";
            echo "Если эта ошибка повторяется, сообщите в службу поддержки.<br><br>";
            echo "&nbsp;&nbsp;&nbsp;Информацию об состоянии Вашего счета вы можете получить в службе поддержки";
         }
         echo "</td><td width='30'>&nbsp;</td></tr></table>";
                   

      }

   }
?>
</center>

</body>

</html>

